# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
