# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.PositiveIntegerField(default=None, max_length=40, null=True),
        ),
    ]
