# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import posts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(null=True, upload_to=posts.utils.generate_imagename),
        ),
    ]
