# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
