# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expiry_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
