# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20161225_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.TextField(default=None, max_length=40, null=True),
        ),
    ]
